export const GET_BRILLOS = "GET_BRILLO"
export const GET_BRILLOS_OK = "GET_BRILLO_OK"
export const GET_BRILLOS_FAIL = "GET_BRILLO_FAIL"


export const GET_SINGLE_BRILLO = "GET_SINGLE_BRILLO"
export const GET_SINGLE_BRILLO_OK = "GET_SINGLE_BRILLO_OK"
export const GET_SINGLE_BRILLO_FAIL = "GET_SINGLE_BRILLO_FAIL"